PythonLearn/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using PythonLearn.Domain.Entity;
using PythonLearn.DAL;
using PythonLearn.Models;
using System.Diagnostics;
using PythonLearn.DAL.Repositories;
using University.DAL.Interfaces;
using PythonLearn.Domain.ViewModel.User;
using PythonLearn.Service.interfaces;
using PythonLearn.Domain.ViewModel.Article;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using System.Net;
using PythonLearn.Service.implementation;
using Microsoft.AspNetCore.Identity;
using PythonLearn.DAL.Migrations;

namespace PythonLearn.Controllers
{
    public class ArticleController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IArticleService _service;
        private readonly IUserService _userService;

        public ArticleController(ILogger<HomeController> logger, IArticleService service, IUserService userService)
        {
            _logger = logger;
            _service = service;
            _userService= userService;
        }
        
        /*
        public async Task<IActionResult> Show()
        {
            var article = await _service.GetArticleAsync(4);
            return View(article.Data);
        }*/

        [HttpGet]
        public async Task<IActionResult> Articles()
        {
            var articles = await _service.GetArticlesAsync();
            return View(articles.Data);
        }

       


        [HttpGet]
        public async Task<IActionResult> Article(int id)
        {
            var fullArticle = await _service.GetCompleteArticle(id);
            return View(fullArticle.Data);
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CompleteArticle article)
        {
            var TxtInfo = HttpContext.Request.Form["content"].ToString();
            var user = _userService.GetUsersAsync().Result.Data.FirstOrDefault(x => x.Login == User.Identity.Name);
            ModelState.ClearValidationState(nameof(CompleteArticle));

            article.ArticleText = TxtInfo;
            article.UserId = user.Id;
 
            
            var isValid = TryValidateModel(article, nameof(CompleteArticle));
            var test = ModelState.IsValid;
            if (isValid)
            {
                var response = await _service.CreateArticleWithTitle(article);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                { 
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", response.Description);
            }
            return View(article);
        }

        [HttpPost]
        public ActionResult UplodImage(List<IFormFile> files, string folder)
        {

            if (folder == null)
            { 
                folder = Path.GetRandomFileName();
            }
           
            string folderPath = Path.Combine("wwwroot", "images/articles/", folder);
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            var filePath = "";
            foreach (IFormFile photo in Request.Form.Files)
            {
                string serverMapPath = Path.Combine("wwwroot", "images/articles/", folder, photo.FileName);
                using (var stream = new FileStream(serverMapPath, FileMode.Create))
                {
                    photo.CopyToAsync(stream);
                }
                filePath = "https://localhost:7265/images/articles/" + folder +"/" + photo.FileName;
            }
            return Json(new { url = filePath });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PythonLearn/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PythonLearn.Domain.Entity;
using PythonLearn.Domain.Enum;
using PythonLearn.Domain.ViewModel.Article;
using PythonLearn.Domain.ViewModel.Course;
using PythonLearn.Service.implementation;
using PythonLearn.Service.interfaces;
using System.Text;

namespace PythonLearn.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _service;

        public CourseController(ICourseService service)
        {
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> Main(int id)
        {
            var course = await _service.GetFullCourse(id);
            return View(course.Data);
        }

        [HttpGet]
        public async Task<IActionResult> Lecture(int id)
        {
            var lecture = await _service.GetLecture(id);
            var viewLecture = new LectureViewModel()
            {
                Name = lecture.Data.Name,
                Text = lecture.Data.Text,
            };
            return View(viewLecture);
        }

        [HttpGet]
        public async Task<IActionResult> CreateTest()
        {
            var lessons = await _service.GetLessons();

            ViewBag.Lessons = new SelectList(lessons.Data, "Id", "Name");

            return View();
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateLecture()
        {
            var lessons = await _service.GetLessons();

            ViewBag.Lessons = new SelectList(lessons.Data, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateTest([FromBody] TestViewModel test)
        {
            var testEntity = new Test()
            {
                LessonId = test.Lesson,
                Name = test.Name
            };

            await _service.CreateTest(testEntity);

            foreach (var questionViewModel in test.Questions)
            {
                var correctAnswer = new StringBuilder();

                foreach (var answer in questionViewModel.Options)
                {
                    correctAnswer.Append(answer.ToString());
                }
                var questionEntity = new Question
                {
                    TestId = testEntity.Id,
                    Text = questionViewModel.Text,
                    CorrectAnswer = correctAnswer.ToString()
                };

                await _service.CreateQuest(questionEntity);

                foreach (var optionViewModel in questionViewModel.Options)
                {
                    var optionEntity = new Answer
                    {
                        QuestionId = questionEntity.Id,
                        Text = optionViewModel.Text,
                        IsCorrect = optionViewModel.IsCorrect
                    };

                    await _service.CreateAnswer(optionEntity);
                }
            }
            return Ok();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateLecture(LectureViewModel lecture)
        {
            var TxtInfo = HttpContext.Request.Form["content"].ToString();
            lecture.Text= TxtInfo;

            if (ModelState.IsValid)
            {
                var response = await _service.CreateLecture(lecture);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", response.Description);
            }
            return View(lecture);
        }

        [HttpPost]
        public ActionResult UplodImage(List<IFormFile> files, string folder)
        {

            if (folder == null)
            {
                folder = Path.GetRandomFileName();
            }

            string folderPath = Path.Combine("wwwroot", "images/lectures/", folder);
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            var filePath = "";
            foreach (IFormFile photo in Request.Form.Files)
            {
                string serverMapPath = Path.Combine("wwwroot", "images/lectures/", folder, photo.FileName);
                using (var stream = new FileStream(serverMapPath, FileMode.Create))
                {
                    photo.CopyToAsync(stream);
                }
                filePath = "https://localhost:7265/images/lectures/" + folder + "/" + photo.FileName;
            }
            return Json(new { url = filePath });
        }

    }
}

PythonLearn/Views/Course/CreateLecture.cshtml
@model PythonLearn.Domain.ViewModel.Course.LectureViewModel

@{
    ViewData["Title"] = "Python";
}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="~/js/ckeditor5/ckeditor.js"></script>
    <script src="https://kit.fontawesome.com/c2c8ebeca3.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="js/slick-1.8.1/slick/slick.css" />
    <title>Обучение python</title>
</head>

<body>
    <div id="toTop"><i class="fas- fa-chevron-up"></i></div>
    <header class="menu-bar">
        <div class="container">
            <div class="row">
                <div class="col-xl-1 logo-bar">
                    <img src="~/images/logo.png" alt="Main logo" class="logo">
                    <button class="menu-icon">
                        <i class="fas fa-bars"></i>
                    </button>
                </div>
                <div class="col-xl-9 ml-auto align-self-center">
                    <nav>
                        <ul class="menu d-flex justify-content-end">
                            <li class="menu__item"><a href="/"><i class="fas fa-home"></i></a></li>
                            <li class="menu__item"><a href="#about">О нас</a></li>
                            <li class="menu__item"><a href="#service">Возможности</a></li>
                            <li class="menu__item"><a href="#portfolio">Обучение</a></li>
                            <li class="menu__item"><a href="#blog">Блог</a></li>
                            <li class="menu__item"><a href="#contact">Контакты</a></li>
                            <li class="menu__item">Kostaqw</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <section class="aboutContent" id="about">
        <form method="post" asp-controller="Course" asp-action="CreateLecture" enctype="multipart/form-data">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="form-group mt-4">
                            <label for="lessonSelect">Выберите урок:</label>
                            <select asp-for="LessonId" class="form-control" id="lessonSelect" asp-items="@ViewBag.Lessons"></select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label id="lectureName" for="testName">Название лекции</label>
                        <input asp-for="Name" type="text" class="form-control" id="testName" />
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col text-center">
                        <textarea name="content" id="editor" class="form-control"></textarea>
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col text-center">
                        <button type="submit" class="register_button" value="ОТПРАВИТЬ">Создать</button>
                    </div>
                </div>
            </div>
        </form>
    </section>

    
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
            integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
            crossorigin="anonymous"></script>

    <script src="js/jquery-3.6.3.js"></script>
    <script type="text/javascript" src="js/slick-1.8.1/slick/slick.min.js"></script>
    <script src="js/main.js"></script>
    
    <script>
        class MyUploadAdapter 
        {
            constructor(loader) {
                // The file loader instance to use during the upload. It sounds scary but do not
                // worry — the loader will be passed into the adapter later on in this guide.
                this.loader = loader;
            }
            upload() {
                return this.loader.file
                    .then(file => new Promise((resolve, reject) => {
                        this._initRequest();
                        this._initListeners(resolve, reject, file);
                        this._sendRequest(file);
                    }));
            }

            // Aborts the upload process.
            abort() {
                if (this.xhr) {
                    this.xhr.abort();
                }
            }

            _initRequest() {
                const xhr = this.xhr = new XMLHttpRequest();
                // Note that your request may look different. It is up to you and your editor
                // integration to choose the right communication channel. This example uses
                // a POST request with JSON as a data structure but your configuration
                // could be different.

                xhr.open('POST', '@Url.Action("UplodImage","Article")', true);
                xhr.responseType = 'json';
            }

            _initListeners(resolve, reject, file) {
                const xhr = this.xhr;
                const loader = this.loader;
                const genericErrorText = `Couldn't upload file: ${file.name}.`;

                xhr.addEventListener('error', () => reject(genericErrorText));
                xhr.addEventListener('abort', () => reject());
                xhr.addEventListener('load', () => {
                    const response = xhr.response;

                    // This example assumes the XHR server's "response" object will come with
                    // an "error" which has its own "message" that can be passed to reject()
                    // in the upload promise.
                    //
                    // Your integration may handle upload errors in a different way so make sure
                    // it is done properly. The reject() function must be called when the upload fails.
                    if (!response || response.error) {
                        return reject(response && response.error ? response.error.message : genericErrorText);
                    }

                    // If the upload is successful, resolve the upload promise with an object containing
                    // at least the "default" URL, pointing to the image on the server.
                    // This URL will be used to display the image in the content. Learn more in the
                    // UploadAdapter#upload documentation.
                    resolve({
                        default: response.url
                    });
                });

                // Upload progress when it is supported. The file loader has the #uploadTotal and #uploaded
                // properties which are used e.g. to display the upload progress bar in the editor
                // user interface.
                if (xhr.upload) {
                    xhr.upload.addEventListener('progress', evt => {
                        if (evt.lengthComputable) {
                            loader.uploadTotal = evt.total;
                            loader.uploaded = evt.loaded;
                        }
                    });
                }
            }

            // More methods.
            // ...

            // Prepares the data and sends the request.
            _sendRequest(file) {
                // Prepare the form data.
                const data = new FormData();
                var folderName = document.getElementById('lectureName').value;
                data.append('upload', file);
                data.append('folder', folderName);
                // Important note: This is the right place to implement security mechanisms
                // like authentication and CSRF protection. For instance, you can use
                // XMLHttpRequest.setRequestHeader() to set the request headers containing
                // the CSRF token generated earlier by your application.

                // Send the request.
                this.xhr.send(data);
            }
        }
        function MyCustomUploadAdapterPlugin(editor) {
            editor.plugins.get('FileRepository').createUploadAdapter = (loader) => {
                // Configure the URL to the upload script in your back-end here!
                return new MyUploadAdapter(loader);
            };
        }
        ClassicEditor
            .create(document.querySelector('#editor'), 
            {   extraPlugins: [ MyCustomUploadAdapterPlugin ]})
            .then(editor => { window.editor = editor;  })
            .catch(err => { console.error(err.stack); });
</script>

</body>

</html>

PythonLearn/Views/Course/Lecture.cshtml
@model PythonLearn.Domain.ViewModel.Course.LectureViewModel

@{
    ViewData["Title"] = "Python";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://kit.fontawesome.com/c2c8ebeca3.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="js/slick-1.8.1/slick/slick.css" />
    <title>Пользователь</title>
</head>

<body>
    <div id="toTop"><i class="fas fa-chevron-up"></i></div>
    <header class="menu-bar">
        <div class="container">
            <div class="row">
                <div class="col-xl-1 logo-bar">
                    <img src="img/logo.png" alt="Main logo" class="logo">
                    <button class="menu-icon">
                        <i class="fas fa-bars"></i>
                    </button>
                </div>
                <div class="col-xl-9 ml-auto align-self-center">
                    <nav>
                        <ul class="menu d-flex justify-content-end">
                            <li class="menu__item"><a href="index.html"><i class="fas fa-home"></i></a></li>
                            <li class="menu__item"><a href="#about">About</a></li>
                            <li class="menu__item"><a href="#service">Servicing</a></li>
                            <li class="menu__item"><a href="#portfolio">Portfolio</a></li>
                            <li class="menu__item"><a href="#blog">Blog</a></li>
                            <li class="menu__item"><a href="#contact">Contact us</a></li>
                            <li class="menu__item"><i class="fa-solid fa-magnifying-glass"></i></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <header class="user_card_header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-10 ">
                    <p class="usercard__text">@Model.Name</p>
                </div>
            </div>
        </div>
    </header>

    <section class="articles">
        <div class="container ">
            <div class="article ">
                <div class="row">
                    <div class="col-xl-10">
                        <p class="articles__header">
                            @Model.Name
                        </p>
                    </div>
                </div>
                <div class="row article__content">
                    <div class="col-xl-10">
                        @Html.Raw(Model.Text);
                    </div>
                </div>

                <div class="row article__content navigation justify-content-center">
                    <div class="col-xl-3">
                        <a asp-controller="Course" asp-action="Main" asp-route-id="1" > <<Назад </a>
                    </div>
                </div>

    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
            integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
            crossorigin="anonymous"></script>

    <script src="js/jquery-3.6.3.js"></script>
    <script type="text/javascript" src="js/slick-1.8.1/slick/slick.min.js"></script>
    <script src="js/main.js"></script>

</body>

</html>

PythonLearn/Views/Course/Main.cshtml
@model PythonLearn.Domain.ViewModel.Course.FullCourseViewModel

@{
    ViewData["Title"] = "Python";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://kit.fontawesome.com/c2c8ebeca3.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="js/slick-1.8.1/slick/slick.css" />
    <title>Пользователь</title>
</head>

<body>
    <header class="menu-bar">
        <div class="container">
            <div class="row">
                <div class="col-xl-1 logo-bar">
                    <img src="~/images/logo.png" alt="Main logo" class="logo">
                    <button class="menu-icon">
                        <i class="fas fa-bars"></i>
                    </button>
                </div>
                <div class="col-xl-9 ml-auto align-self-center">
                    <nav>
                        <ul class="menu d-flex justify-content-end">
                            <li class="menu__item"><a href="/"><i class="fas fa-home"></i></a></li>
                            <li class="menu__item"><a href="#about">О нас</a></li>
                            <li class="menu__item"><a href="#service">Возможности</a></li>
                            <li class="menu__item"><a href="#portfolio">Обучение</a></li>
                            <li class="menu__item"><a href="#blog">Блог</a></li>
                            <li class="menu__item"><a href="#contact">Контакты</a></li>
                            <li class="menu__item">
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <h1>@Model.Name</h1>
    <p>@Model.Description</p>

    <div class="container">
        <h2>Курс:</h2>
        <ul class="list-group">
            @foreach (var lesson in Model.Lessons)
            {
                <li class="list-group-item">
                    <h4><a href="@Url.Action("Lesson", "Course", new { lessonId = lesson.Id })">@lesson.Name</a></h4>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <h3>Лекции:</h3>
                                <ul class="list-group">
                                    @foreach (var lecture in lesson.Lectures)
                                    {
                                        <li class="list-group-item">
                                            <a href="@Url.Action("Lecture", "Course", new { Id = lecture.Id })">@lecture.Name</a>
                                        </li>
                                    }
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <h3>Практические задачи:</h3>
                                <ul class="list-group">
                                    @foreach (var practice in lesson.Practices)
                                    {
                                        <li class="list-group-item">
                                            <a href="@Url.Action("Practice", "Course", new { practiceId = practice.Id })">@practice.Question</a>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="container">
                        <h3>Тесты:</h3>
                        <ul class="list-group">
                            @foreach (var test in lesson.Tests)
                            {
                                <li class="list-group-item">
                                    <a href="@Url.Action("Test", "Course", new { testId = test.Id })">Test @test.Name</a>
                                </li>
                            }
                        </ul>
                    </div>
                </li>
            }
        </ul>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
            integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
            crossorigin="anonymous"></script>

    <script src="js/jquery-3.6.3.js"></script>
    <script type="text/javascript" src="js/slick-1.8.1/slick/slick.min.js"></script>
    <script src="js/main.js"></script>

</body>

</html>